import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-surface-950">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-surface-800">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <div className="flex justify-between items-center h-14 sm:h-16">
            <Link to="/" className="flex items-center gap-2 sm:gap-3">
              <div className="w-7 h-7 sm:w-8 sm:h-8 rounded-lg bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center">
                <svg className="w-4 h-4 sm:w-5 sm:h-5 text-surface-950" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10 2a1 1 0 011 1v1.323l3.954 1.582 1.599-.8a1 1 0 01.894 1.79l-1.233.616 1.738 5.42a1 1 0 01-.285 1.05A3.989 3.989 0 0115 15a3.989 3.989 0 01-2.667-1.019 1 1 0 01-.285-1.05l1.715-5.349L11 6.477V16h2a1 1 0 110 2H7a1 1 0 110-2h2V6.477L6.237 7.582l1.715 5.349a1 1 0 01-.285 1.05A3.989 3.989 0 015 15a3.989 3.989 0 01-2.667-1.019 1 1 0 01-.285-1.05l1.738-5.42-1.233-.617a1 1 0 01.894-1.788l1.599.799L9 4.323V3a1 1 0 011-1z" />
                </svg>
              </div>
              <span className="font-serif text-base sm:text-lg font-semibold text-white">Heritage</span>
            </Link>
            <Link to="/builder" className="btn-primary text-xs sm:text-sm py-1.5 sm:py-2 px-3 sm:px-6">
              Create
            </Link>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="pt-20 sm:pt-24 pb-12 sm:pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-2xl sm:text-4xl font-bold text-white mb-4 sm:mb-8">Terms of Service</h1>
          <p className="text-gray-400 mb-6 sm:mb-8 text-sm sm:text-base">Last updated: January 8, 2026</p>

          <div className="prose prose-invert max-w-none space-y-6 sm:space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-400 leading-relaxed">
                By accessing or using Heritage AI ("the Service"), you agree to be bound by these Terms of Service.
                If you do not agree to these terms, please do not use the Service. We reserve the right to
                modify these terms at any time, and your continued use constitutes acceptance of any changes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="text-gray-400 leading-relaxed">
                Heritage AI is an AI-powered family tree generation service that creates artistic representations
                of family relationships. The Service allows users to input family member information, upload photos,
                and generate unique family tree artwork using artificial intelligence.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts</h2>
              <ul className="list-disc list-inside text-gray-400 space-y-2">
                <li>You may use the Service as a guest or create an account</li>
                <li>You are responsible for maintaining the security of your account</li>
                <li>You must provide accurate and complete information</li>
                <li>You must be at least 13 years old to use the Service</li>
                <li>One person may not maintain multiple accounts</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. User Content</h2>
              <p className="text-gray-400 leading-relaxed mb-4">By uploading content to Heritage AI, you represent that:</p>
              <ul className="list-disc list-inside text-gray-400 space-y-2">
                <li>You own or have rights to use the photos and information you upload</li>
                <li>You have consent from individuals whose photos you upload</li>
                <li>Your content does not violate any laws or third-party rights</li>
                <li>Your content is not offensive, harmful, or inappropriate</li>
              </ul>
              <p className="text-gray-400 leading-relaxed mt-4">
                You retain ownership of your content. By uploading, you grant Heritage AI a limited license
                to process and display your content solely for providing the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. Generated Artwork</h2>
              <p className="text-gray-400 leading-relaxed mb-4">
                Artwork generated by Heritage AI:
              </p>
              <ul className="list-disc list-inside text-gray-400 space-y-2">
                <li>Is created using AI and may not be perfect or accurate</li>
                <li>Is licensed to you for personal, non-commercial use upon purchase</li>
                <li>Should not be used for fraudulent or misleading purposes</li>
                <li>May be used in our marketing with your permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-semibold text-white mb-3 sm:mb-4">6. Pricing and Payments</h2>
              <ul className="list-disc list-inside text-gray-400 space-y-2">
                <li><strong className="text-white">Free:</strong> Generate family tree artwork with watermark</li>
                <li><strong className="text-white">$2.99 per download:</strong> HD quality without watermark</li>
                <li>All payments are processed securely</li>
                <li>Prices may change with notice to users</li>
                <li>All sales are final unless otherwise required by law</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. Refund Policy</h2>
              <p className="text-gray-400 leading-relaxed">
                Due to the digital nature of our product, all sales are generally final. However, if you
                experience technical issues that prevent you from receiving your purchased download,
                please contact us within 7 days for a full refund. We handle refund requests on a
                case-by-case basis.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. Prohibited Uses</h2>
              <p className="text-gray-400 leading-relaxed mb-4">You may not use the Service to:</p>
              <ul className="list-disc list-inside text-gray-400 space-y-2">
                <li>Upload content you don't have rights to use</li>
                <li>Create fraudulent or misleading family trees</li>
                <li>Harass, abuse, or harm others</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to access other users' accounts or data</li>
                <li>Reverse engineer or copy our AI technology</li>
                <li>Use automated systems to access the Service</li>
                <li>Resell generated artwork commercially without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. Intellectual Property</h2>
              <p className="text-gray-400 leading-relaxed">
                The Heritage AI service, including its design, features, and technology, is owned by us
                and protected by intellectual property laws. You may not copy, modify, or distribute
                any part of the Service without permission.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">10. Disclaimer of Warranties</h2>
              <p className="text-gray-400 leading-relaxed">
                THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE
                THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED RESULTS
                WILL MEET YOUR EXPECTATIONS. AI OUTPUT MAY CONTAIN INACCURACIES OR IMPERFECTIONS.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">11. Limitation of Liability</h2>
              <p className="text-gray-400 leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, HERITAGE AI SHALL NOT BE LIABLE FOR ANY
                INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF
                THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE SERVICE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">12. Account Termination</h2>
              <p className="text-gray-400 leading-relaxed">
                We reserve the right to suspend or terminate your account at any time for violation
                of these terms or for any other reason at our discretion. You may also delete your
                account at any time through your account settings or by contacting support.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">13. Governing Law</h2>
              <p className="text-gray-400 leading-relaxed">
                These Terms shall be governed by and construed in accordance with applicable laws.
                Any disputes arising from these terms or the Service shall be resolved through
                binding arbitration or in the courts of competent jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-semibold text-white mb-3 sm:mb-4">14. Contact</h2>
              <p className="text-gray-400 leading-relaxed">
                For questions about these Terms of Service, please contact us at:{' '}
                <a href="mailto:addwish80@gmail.com" className="text-primary-400 hover:text-primary-300">
                  addwish80@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-6 sm:py-8 px-4 sm:px-6 border-t border-surface-800">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-3">
            <div className="w-6 h-6 rounded bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center">
              <svg className="w-4 h-4 text-surface-950" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a1 1 0 011 1v1.323l3.954 1.582 1.599-.8a1 1 0 01.894 1.79l-1.233.616 1.738 5.42a1 1 0 01-.285 1.05A3.989 3.989 0 0115 15a3.989 3.989 0 01-2.667-1.019 1 1 0 01-.285-1.05l1.715-5.349L11 6.477V16h2a1 1 0 110 2H7a1 1 0 110-2h2V6.477L6.237 7.582l1.715 5.349a1 1 0 01-.285 1.05A3.989 3.989 0 015 15a3.989 3.989 0 01-2.667-1.019 1 1 0 01-.285-1.05l1.738-5.42-1.233-.617a1 1 0 01.894-1.788l1.599.799L9 4.323V3a1 1 0 011-1z" />
              </svg>
            </div>
            <span className="text-gray-500 text-sm">Heritage</span>
          </div>
          <div className="flex items-center gap-6 text-sm text-gray-500">
            <Link to="/privacy" className="hover:text-gray-300 transition-colors">Privacy</Link>
            <Link to="/terms" className="hover:text-gray-300 transition-colors">Terms</Link>
            <Link to="/contact" className="hover:text-gray-300 transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
